### ISSUE TITLE
How to integrate Portal to YetiForce CRM?

### ISSUE THREAD

**Issue by quocnho** [YetiForceCompany/YetiForcePortal#1]
Dear all, I have downloaded YetiForce CRM and Portal then, in root folder, I create 2 folders:
crm and portal. After that, how can I integrate portal to CRM?
If anyone done successful, please help me step by step?
Thanks in advance!

**Comment by mariuszkrzaczkowski** [comment]
In the file api\config.php you need to uncomment the line 'yetiportal',

**Comment by quocnho** [comment]
Let me see!

**Comment by quocnho** [comment]
Sorry about my knowledge. Can you help me to guild step by step?

**Comment by waw555** [comment]
I can not run the portal on the login page was not given access to the mail does not arrive, password recovery does not want to work. Writes, the user is not found in the system.

In the CRM system uncommented 'customerportal', and 'yetiportal',

In the portal settings prescribed path to the CRM system

**Comment by mariuszkrzaczkowski** [comment]
1. Uncomment 'yetiportal' w api/config.php
2. Enable workflow generating access to the portal, System Settings > Other Settings > Workflow > Generate Customer Login Details > in the bookmark 'Add Tasks' mark 'Create Portal Login Details' as 'Active'
3. Enable workflow that sends acess to the portal, System Settings > Other Settings > Workflow >  Send Customer Login Details > in the bookmark 'Add Tasks' mark 'Send Customer Login Details' as 'Active'
4. A Contact needs to have the 'Primary Email' field filled in and ticked the two items: 'Permission to send emails' and 'Portal User'

**Comment by quocnho** [comment]
Thank you so much! 
Have a good day!

**Comment by waw555** [comment]
Generate Customer Login Details ????

![error portal workflow](https://cloud.githubusercontent.com/assets/1402355/5852471/2c7783e4-a239-11e4-9e6d-08718660883e.JPG)

**Comment by mariuszkrzaczkowski** [comment]
Show only workflow in module contacts you will see.

**Comment by waw555** [comment]
![errorportal 1](https://cloud.githubusercontent.com/assets/1402355/5853381/f0e6548e-a244-11e4-931c-f89226d00afa.JPG)
![errorportal2](https://cloud.githubusercontent.com/assets/1402355/5853386/f6f6a82e-a244-11e4-91d7-679eb93f0a56.JPG)
![errorportal3](https://cloud.githubusercontent.com/assets/1402355/5853394/01481362-a245-11e4-814a-161fc05cd200.JPG)
![errorportal4](https://cloud.githubusercontent.com/assets/1402355/5853396/05eaa9a2-a245-11e4-9478-98dc3db0f0c5.JPG)

**Comment by waw555** [comment]
![sheduler](https://cloud.githubusercontent.com/assets/1402355/5853467/c8960c12-a245-11e4-8df2-02516747229d.JPG)

**Comment by mariuszkrzaczkowski** [comment]
Make sure you correctly set the values in the below example.
![portal](https://cloud.githubusercontent.com/assets/10198654/6199723/5eed182e-b455-11e4-8b2b-6566aeb2ff21.png)

Keep in mind that the generation of the access is performed on the change in the User Portal

![active portal](https://cloud.githubusercontent.com/assets/10198654/6199724/63588f9c-b455-11e4-88df-8a16dbaa38eb.png)
