### ISSUE TITLE
Problem z kodowaniem polskich znaków

### ISSUE THREAD

**Issue by doriandudzisz** [YetiForceCompany/YetiForcePortal#21]
Witam, plik csv wygenerowany przez ten sam crm, który importuje również dane bez zmian powoduje utratę polskich znaków, jak to rozwiazać?

**Comment by bpabiszczak** [comment]
Proszę wywołać błąd na wersji testowej i załącznik plik, który był wyeksportowany i który był importowany. Wersja testowa tutaj: https://test.yetiforce.com

**Comment by doriandudzisz** [comment]
własnie blad dotyczy crm machnolem sie, nie mniej jednak bład w demie nie wystepuje

**Comment by doriandudzisz** [comment]
tylko dziwne jest zachowanie ze raz crm wyswietla polski znak innym razem nie....

**Comment by bpabiszczak** [comment]
Problem pewnie dotyczy niepoprawnej instalacji lub innego czynnika. Przy okazji proszę przeczytać ten artykuł jak się zgłasza błędy: https://yetiforce.com/pl/pomys%C5%82y,-zmiany,-b%C5%82%C4%99dy/b%C5%82%C4%99dy/125-jak-zg%C5%82asza%C4%87-b%C5%82%C4%99dy.html

**Comment by doriandudzisz** [comment]
doprawdy jesteście bardzo pomocni.... ciekawe jak pomagacie tym co chca wam placic
