### ISSUE TITLE
No English translations in tables in module summary

### ISSUE THREAD

**Issue by KatarzynaUlichnowska** [YetiForceCompany/YetiForcePortal#4]
![image001](https://cloud.githubusercontent.com/assets/10218164/5914996/97b4bb4e-a5ff-11e4-8cac-d154620d6ebb.png)

Issue found by Roy Snuverink

**Comment by waw555** [comment]
Write me how you installed portal, as I can not get it to work

**Comment by mariuszkrzaczkowski** [comment]
Short description of how to install can be found in issue https://github.com/YetiForceCompany/YetiForceCRM/issues/37#issuecomment-68238221

**Comment by mariuszkrzaczkowski** [comment]
Fixed in 1.3.5 RC
https://github.com/YetiForceCompany/YetiForceCRM/commit/84e5aa9efe6e320b23ae8a3d4c753168e9eb32e6
