### ISSUE TITLE
Problem z instalacja

### ISSUE THREAD

**Issue by doriandudzisz** [YetiForceCompany/YetiForcePortal#80]
Mimo wykonania instalacji krok po kroku, z powodu aktualizacji crm z 1.4 do 2.0 nie mogę zalogować się do portalu klienta, wgrałem aktuana wersje nadal nie mogę sie zalogować, ale przypomnienie hasła działa....

**Comment by bpabiszczak** [comment]
https://yetiforce.com/pl/dokumentacja-programisty/b%C5%82%C4%99dy/125-jak-zg%C5%82asza%C4%87-b%C5%82%C4%99dy.html

**Comment by doriandudzisz** [comment]
rozumiem ze tym linkiem dostaje odpowiedz radz sobie człowieku sam?

**Comment by bpabiszczak** [comment]
Nie tym linkiem dostajesz odpowiedź: szanuj nasz czas i jeżeli chcesz otrzymać pomoc, to zrób minimum to co jest napisane w dokumentacji, czyli włącz logi i zobacz co one pokazują a następnie zgłoś prawidłowo zgłoszenie, tak abyśmy nie musieli zgadywać co jest błędem, co pokazują logi i co autor ma na myśli.

**Comment by doriandudzisz** [comment]
https://www.dropbox.com/s/ub7id98bbfry34m/phpError.log?dl=0

https://www.dropbox.com/s/26ea841pbue2vg9/yetiportal.log?dl=0

jeżel czegos jeszcze brakuje prosze o info a podeśle,

ps czas osob zgłaszajacych problem tez warto uszanować i naprowadzic czego szukać pod danym linkiem, tym bardziej ze na dzien dobry czytam kiedy nie zglaszac

**Comment by bpabiszczak** [comment]
Pierwsze co mi się rzuca w oczy to:
1. Czy aby na pewno serwer ma poprawną konfiguracje zgodnie z tym opisem: https://yetiforce.com/pl/dokumentacja-administratora/instalacja/99-wymagania-dla-serwera-www.html, widzę tam takie błędy jak: PHP Strict Standards a w logach nie powinno być ich widać.

2. Czy masz utworzony folder dla sesjii [niektóre hostingi tego wymagają np. w home trzeba mieć folder tmp bo są takie błędy jak: session_start(): open(cache/session/sess_ucmfbhhglv2n9odaoggnesru57, O_RDWR) failed: No such file or directory (2) a one mogą wynikać z braku folderu albo braku uprawnień odpowiednich na plikach i folderach. [08-Apr-2015 09:26:46 Europe/Sarajevo] PHP Warning:  Unknown: Failed to write session data (files). Please verify that the current setting of session.save_path is correct (cache/session) in Unknown on line 0

3. Jak wyglądały logi przy aktualizacji? Czy na pewno tam się wykonało wszystko poprawnie, bo sądząc po logach ma Pan dużo błędów, których być nie powinno.

**Comment by doriandudzisz** [comment]
Ad.1 Serwer był konfigurowany pod włąsnie te wytyczne podane na weszej stronie 

Folder cache/session istnieje chmod 755

Aktulalizacja wykonala logów w tedy nie sprawdzalem ponieważ wygladało że chodzi jak należy schody zaczeły sie przy Portalu Klienta

**Comment by bpabiszczak** [comment]
Proszę usunąć logi podane powyżej. 
Jeżeli jest taka możliwość, proszę o przesłanie na maila dostępu do środowiska testowego, gdzie ma Pan wszystko skonfigurowane, tak abyśmy sprawdzili przyczynę co jest nieprawidłowo. Z aktualnych logów wynika, że ma Pan przede wszystkim niepoprawnie skonfigurowany serwer pod aplikacje.

**Comment by doriandudzisz** [comment]
dobra ten problem zarzegnany juz, mam jeszcze pytanie czy da sie zarzadzać kolumanmi dla danego modułu w portalu klienta w vtigerze byla taka opcja tutaj jej nie widze

**Comment by doriandudzisz** [comment]
oraz jak wystawic korekte to faktury

**Comment by bpabiszczak** [comment]
Fajnie by było, abyś napisał co było problemem, może się innym przydać. 

Jeden błąd/pytanie jedno zgłoszenie/issue/

Nie wiem o jakim zarządzaniu kolumnami mówisz w Vtiger, prześlij mi link do ich wersji demo [do narzędzia] abym mógł się do tego ustosunkować. Dodaj to w oddzielnym zgłoszeniu. 

Na chwilę obecną nie ma jeszcze dodanych korekt do faktur, planujemy to dodać w wersji 2.3/2.4.
